FROM mhart/alpine-node:15.12.0 AS builder
WORKDIR /usr/app
COPY ["./package.json", "./"]
RUN npm install
COPY . .

FROM mhart/alpine-node:15.12.0
WORKDIR /usr/app/fastagram-backend
COPY --from=builder /usr/app/ /usr/app/fastagram-backend

EXPOSE 5432
RUN apk add --no-cache make gcc g++ python3 && \
    npm rebuild bcrypt --build-from-source && \
    apk del make gcc g++ python3
CMD ["npm","run", "dev"]