FROM mhart/alpine-node:15.12.0 AS builder
WORKDIR /app
RUN mkdir ./dist
COPY ["package.json", "./"]
RUN npm install
COPY . .
RUN npm run build


FROM mhart/alpine-node:15.12.0
WORKDIR /api
RUN mkdir ./dist
COPY --from=builder /app/dist/ /api/dist/
COPY --from=builder /app/prod-config/package.json /api/
RUN npm install --only=production
RUN npm uninstall typescript
CMD [ "node", "./dist/server.js" ]