version: '3'
services:
  api:
    container_name: api
    read_only: true
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    image: api:1.0
    ports:
      - 4000:4000
    restart: always
    volumes:
      - .:/usr/app/fastagram-backend
      - /usr/app/fastagram-backend/node_modules
    env_file:
      - ./.env
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres:13.2
    env_file:
      - ./.env
    volumes:
      - pg-vol:/data/db
    ports:
      - 5432:5432
volumes:
  pg-vol:
