export { default as authRoute } from './auth';
export { default as dashboardRoute } from './dashboard';
export { default as profileRoute } from './profile';
export { default as searchRoute } from './search';
export { default as commentRoute } from './comment';
export { default as likeRoute } from './like';
export { default as error404 } from './error404';
export { default as globalError } from './globalError';
export { default as init } from './init';
